#!/bin/sh
projectfolder="/mnt/project/lottery_main"
binlocation="$projectfolder/vendor/bin"
phpstanlocation="$binlocation/phpstan"
autoloadPath="$projectfolder/vendor/autoload.php"
RULESET="$projectfolder/phpcs.xml"
helper="$projectfolder/_ide_helper.php"
neonfile="$projectfolder/phpstan.neon"
phpcslocation="$binlocation/phpcs"
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")
if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi
PASS=true
echo "\nValidating PHPCS:\n"
# Check for phpcs
which "$phpcslocation" &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t\033[41mPlease install PHPCS\033[0m"
  exit 1
fi

for FILE in $STAGED_FILES
do
  dir=$(pwd)
  echo $dir
  tail=$(echo $dir | cut -d'/' -f5-)
  filelocation=$projectfolder/$tail/$FILE
  echo "Here is filelocation $filelocation"
  "$phpcslocation" --standard="$RULESET" "$FILE"
  EXIT_STATUS=$?
  echo "exist status is $EXIT_STATUS"
##################################################################################
echo "Starting To Run Code Quality"
echo "autoload path is $autoloadPath"
echo "file path is $FILE"
php "$projectfolder/artisan" code:analyse --error-format=table --autoload-file=$helper -a $autoloadPath -c "$neonfile" --paths="$filelocation"
  STAN_STATUS=$?
  echo "STAN status is $STAN_STATUS"
    if [ "$STAN_STATUS" -eq "0" ]; then
      echo 'passed'
    else
      echo "$STAN_STATUS"
      echo "Code Quality Test Failed"
      exit 1;
    fi
 ##################################################################################
    if [ "$EXIT_STATUS" -eq "0" ]; then
  echo "\t\033[32mPHPCS Passed: $FILE\033[0m"
  else
    echo "\t\033[41mPHPCS Failed: $FILE\033[0m"
    PASS=false
  fi
done

echo "\nPHPCS validation completed!\n"

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass PHPCS but do not. Please fix the PHPCS errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
