#!/bin/sh
container="30dd0e274e1a"
docker=1
projectfolder="/var/www/multisites"
phpcsbin="$projectfolder/vendor/bin"
phpcslocation="$phpcsbin/phpcs"
RULESET=/var/www/multisites/phpcs.xml

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "\nValidating PHPCS:\n"

# Check for phpcs
result=$(docker exec -i ${container} which ${phpcslocation})
echo $result
$result &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t\033[41mPlease install PHPCS\033[0m nValidating"
  exit 1
fi

for FILE in $STAGED_FILES
do
  echo "RULESET are $RULESET and  FILE are $FILE"
  dir=$(pwd)
  echo $dir
  tail=$(echo $dir | cut -d'/' -f5-)
  filelocation=$projectfolder/$tail/$FILE
  echo "Here is filelocation $filelocation and here is  phpcslocation $phpcslocation"
  docker exec ${container} bash -c "cd $phpcsbin;\
./phpcs --standard=$RULESET $filelocation"
  # docker exec -i ${container} ${phpcslocation} --standard="$RULESET" "$filelocation"
  if [[ "$?" == 0 ]]; then
    echo "\t\033[32mPHPCS Passed: $FILE\033[0m result"
  else
    echo "\t\033[41mPHPCS Failed: $FILE\033[0m"
    PASS=false
  fi
done

echo "\nPHPCS validation completed!\n"

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass PHPCS but do not. Please fix the PHPCS errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?