<?php

use Illuminate\Database\Seeder;

class BackendAdminRechargehumanLogsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('backend_admin_rechargehuman_logs')->delete();
        
        \DB::table('backend_admin_rechargehuman_logs')->insert(array (
            0 => 
            array (
                'id' => 13,
                'type' => 2,
                'in_out' => 0,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => 1,
                'user_name' => 'Dr. Taurean Nader1',
                'amount' => '300.00',
                'comment' => '[给用户人工充值]==>-300|[目前额度]==>1400',
                'audit_flow_id' => 265,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
            ),
            1 => 
            array (
                'id' => 14,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 4,
                'super_admin_name' => 'york',
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '99999999.99',
                'comment' => '[人工充值额度操作]==>+100000000|[目前额度]==>100000000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-09 11:16:43',
                'created_at' => '2019-05-09 11:16:43',
            ),
            2 => 
            array (
                'id' => 15,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 4,
                'super_admin_name' => 'york',
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '1000.00',
                'comment' => '[人工充值额度操作]==>+1000|[目前额度]==>1000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-09 14:20:57',
                'created_at' => '2019-05-09 14:20:57',
            ),
            3 => 
            array (
                'id' => 16,
                'type' => 2,
                'in_out' => 0,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => 500,
                'user_name' => 'Miss Alison Pfannerstill499',
                'amount' => '11.00',
                'comment' => '[给用户人工充值]==>-11|[目前额度]==>989',
                'audit_flow_id' => 249,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-09 14:41:16',
                'created_at' => '2019-05-09 14:21:08',
            ),
            4 => 
            array (
                'id' => 17,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 4,
                'super_admin_name' => 'york',
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '123.00',
                'comment' => '[人工充值额度操作]==>+123|[目前额度]==>1112',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-09 14:29:28',
                'created_at' => '2019-05-09 14:29:28',
            ),
            5 => 
            array (
                'id' => 18,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+3888|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            6 => 
            array (
                'id' => 19,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+3888|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            7 => 
            array (
                'id' => 20,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+3888|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            8 => 
            array (
                'id' => 21,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+3888|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            9 => 
            array (
                'id' => 22,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'name',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+5000|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            10 => 
            array (
                'id' => 23,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'name',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+5000|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            11 => 
            array (
                'id' => 24,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'name',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+5000|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            12 => 
            array (
                'id' => 25,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'name',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+5000|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            13 => 
            array (
                'id' => 26,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 1,
                'super_admin_name' => 'Harris',
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '7.00',
                'comment' => '[人工充值额度操作]==>+7|[目前额度]==>5007',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-10 15:42:05',
                'created_at' => '2019-05-10 15:42:05',
            ),
            14 => 
            array (
                'id' => 27,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 23,
                'super_admin_name' => 'Diana',
                'admin_id' => 25,
                'admin_name' => '122324354654',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '99999999.99',
                'comment' => '[人工充值额度操作]==>+1.0E+43|[目前额度]==>1.0E+43',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-11 16:16:56',
                'created_at' => '2019-05-11 16:16:56',
            ),
            15 => 
            array (
                'id' => 28,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'name',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10000|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-12 00:00:15',
                'created_at' => '2019-05-12 00:00:15',
            ),
            16 => 
            array (
                'id' => 29,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'name',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10000|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-12 00:00:15',
                'created_at' => '2019-05-12 00:00:15',
            ),
            17 => 
            array (
                'id' => 30,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'name',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10000|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-12 00:00:15',
                'created_at' => '2019-05-12 00:00:15',
            ),
            18 => 
            array (
                'id' => 31,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 4,
                'super_admin_name' => 'york',
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '100.00',
                'comment' => '[人工充值额度操作]==>+100|[目前额度]==>100',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-23 17:34:29',
                'created_at' => '2019-05-23 17:34:29',
            ),
            19 => 
            array (
                'id' => 32,
                'type' => 2,
                'in_out' => 0,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'york888',
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'amount' => '10.00',
                'comment' => '[给用户人工充值]==>-10|[目前额度]==>9990',
                'audit_flow_id' => 257,
                'status' => 2,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-23 17:45:10',
                'created_at' => '2019-05-23 17:42:21',
            ),
            20 => 
            array (
                'id' => 33,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '10.00',
                'comment' => '[充值审核失败额度返还]==>+10.00|[目前额度]==>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-23 17:45:10',
                'created_at' => '2019-05-23 17:45:10',
            ),
            21 => 
            array (
                'id' => 34,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+9900|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-24 00:00:12',
                'created_at' => '2019-05-24 00:00:12',
            ),
            22 => 
            array (
                'id' => 35,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+9900|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-24 00:00:12',
                'created_at' => '2019-05-24 00:00:12',
            ),
            23 => 
            array (
                'id' => 36,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+9900|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-24 00:00:12',
                'created_at' => '2019-05-24 00:00:12',
            ),
            24 => 
            array (
                'id' => 37,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 26,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10000|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-24 00:00:12',
                'created_at' => '2019-05-24 00:00:12',
            ),
            25 => 
            array (
                'id' => 38,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 26,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10000|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-24 00:00:12',
                'created_at' => '2019-05-24 00:00:12',
            ),
            26 => 
            array (
                'id' => 39,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 26,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10000|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-24 00:00:12',
                'created_at' => '2019-05-24 00:00:12',
            ),
            27 => 
            array (
                'id' => 40,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 4,
                'super_admin_name' => 'york',
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '199.00',
                'comment' => '[人工充值额度操作]==>+199|[目前额度]==>10199',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-24 11:48:38',
                'created_at' => '2019-05-24 11:48:38',
            ),
            28 => 
            array (
                'id' => 41,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+69801|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-25 00:00:15',
                'created_at' => '2019-05-25 00:00:15',
            ),
            29 => 
            array (
                'id' => 42,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+69801|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-25 00:00:15',
                'created_at' => '2019-05-25 00:00:15',
            ),
            30 => 
            array (
                'id' => 43,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+69801|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-25 00:00:15',
                'created_at' => '2019-05-25 00:00:15',
            ),
            31 => 
            array (
                'id' => 44,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 26,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+70000|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-25 00:00:15',
                'created_at' => '2019-05-25 00:00:15',
            ),
            32 => 
            array (
                'id' => 45,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 26,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+70000|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-25 00:00:15',
                'created_at' => '2019-05-25 00:00:15',
            ),
            33 => 
            array (
                'id' => 46,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 26,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+70000|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-25 00:00:15',
                'created_at' => '2019-05-25 00:00:15',
            ),
            34 => 
            array (
                'id' => 47,
                'type' => 2,
                'in_out' => 0,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'amount' => '10.00',
                'comment' => '[给用户人工充值]==>-10|[目前额度]==>79990',
                'audit_flow_id' => 258,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-25 15:28:44',
                'created_at' => '2019-05-25 15:28:04',
            ),
            35 => 
            array (
                'id' => 48,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-28 00:00:11',
                'created_at' => '2019-05-28 00:00:11',
            ),
            36 => 
            array (
                'id' => 49,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-28 00:00:11',
                'created_at' => '2019-05-28 00:00:11',
            ),
            37 => 
            array (
                'id' => 50,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-05-28 00:00:11',
                'created_at' => '2019-05-28 00:00:11',
            ),
            38 => 
            array (
                'id' => 51,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 4,
                'super_admin_name' => 'york',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'amount' => '1.00',
                'comment' => '[给用户人工充值]==>-1|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-06-06 17:46:51',
                'created_at' => '2019-06-06 17:46:51',
            ),
            39 => 
            array (
                'id' => 52,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 4,
                'super_admin_name' => 'york',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 3,
                'user_name' => 'kiki',
                'amount' => '10000.00',
                'comment' => '[给用户人工充值]==>-10000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-01 19:11:51',
                'created_at' => '2019-07-01 19:11:51',
            ),
            40 => 
            array (
                'id' => 53,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 1,
                'super_admin_name' => 'Harris',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 4,
                'user_name' => 'york34',
                'amount' => '1000.00',
                'comment' => '[给用户人工充值]==>-1000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-03 12:12:31',
                'created_at' => '2019-07-03 12:12:31',
            ),
            41 => 
            array (
                'id' => 54,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 1,
                'super_admin_name' => 'Harris',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 4,
                'user_name' => 'york34',
                'amount' => '10000.00',
                'comment' => '[给用户人工充值]==>-10000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-03 12:12:53',
                'created_at' => '2019-07-03 12:12:53',
            ),
            42 => 
            array (
                'id' => 55,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 23,
                'super_admin_name' => 'Diana',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 4,
                'user_name' => 'york34',
                'amount' => '10000.00',
                'comment' => '[给用户人工充值]==>-10000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-05 14:31:58',
                'created_at' => '2019-07-05 14:31:58',
            ),
            43 => 
            array (
                'id' => 56,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 23,
                'super_admin_name' => 'Diana',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 4,
                'user_name' => 'york34',
                'amount' => '80000.00',
                'comment' => '[给用户人工充值]==>-80000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-05 14:32:19',
                'created_at' => '2019-07-05 14:32:19',
            ),
            44 => 
            array (
                'id' => 57,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 29,
                'super_admin_name' => 'young',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 8,
                'user_name' => 'young',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-08 15:09:39',
                'created_at' => '2019-07-08 15:09:39',
            ),
            45 => 
            array (
                'id' => 58,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 29,
                'super_admin_name' => 'young',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 8,
                'user_name' => 'young',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-08 15:09:49',
                'created_at' => '2019-07-08 15:09:49',
            ),
            46 => 
            array (
                'id' => 59,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 29,
                'super_admin_name' => 'young',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 8,
                'user_name' => 'young',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-08 15:09:59',
                'created_at' => '2019-07-08 15:09:59',
            ),
            47 => 
            array (
                'id' => 60,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 29,
                'super_admin_name' => 'young',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 8,
                'user_name' => 'young',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-08 15:10:12',
                'created_at' => '2019-07-08 15:10:12',
            ),
            48 => 
            array (
                'id' => 61,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 30,
                'super_admin_name' => 'max',
                'admin_id' => 27,
                'admin_name' => 'sami',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '10000.00',
                'comment' => '[人工充值额度操作]==>+10000|[目前额度]==>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-13 14:56:58',
                'created_at' => '2019-07-13 14:56:58',
            ),
            49 => 
            array (
                'id' => 62,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 23,
                'super_admin_name' => 'Diana',
                'admin_id' => 27,
                'admin_name' => 'sami',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '20000.00',
                'comment' => '[人工充值额度操作]==>+20000|[目前额度]==>30000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-15 12:33:25',
                'created_at' => '2019-07-15 12:33:25',
            ),
            50 => 
            array (
                'id' => 63,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 23,
                'super_admin_name' => 'Diana',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 14,
                'user_name' => 'diana111',
                'amount' => '1000.00',
                'comment' => '[给用户人工充值]==>-1000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-15 14:55:59',
                'created_at' => '2019-07-15 14:55:59',
            ),
            51 => 
            array (
                'id' => 64,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 30,
                'super_admin_name' => 'max',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'amount' => '10.00',
                'comment' => '[给用户人工充值]==>-10|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-15 15:19:21',
                'created_at' => '2019-07-15 15:19:21',
            ),
            52 => 
            array (
                'id' => 65,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 30,
                'super_admin_name' => 'max',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 14,
                'user_name' => 'diana111',
                'amount' => '10.00',
                'comment' => '[给用户人工充值]==>-10|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-15 15:19:51',
                'created_at' => '2019-07-15 15:19:51',
            ),
            53 => 
            array (
                'id' => 66,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+90000|[目前额度]=>>90000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-16 00:00:01',
                'created_at' => '2019-07-16 00:00:01',
            ),
            54 => 
            array (
                'id' => 67,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 26,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+90000|[目前额度]=>>90000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-16 00:00:01',
                'created_at' => '2019-07-16 00:00:01',
            ),
            55 => 
            array (
                'id' => 68,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 34,
                'admin_name' => 'diana111',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+90000|[目前额度]=>>90000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-16 00:00:01',
                'created_at' => '2019-07-16 00:00:01',
            ),
            56 => 
            array (
                'id' => 69,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 36,
                'admin_name' => '测试1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+90000|[目前额度]=>>90000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-16 00:00:01',
                'created_at' => '2019-07-16 00:00:01',
            ),
            57 => 
            array (
                'id' => 70,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 38,
                'admin_name' => 'max111',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+90000|[目前额度]=>>90000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-16 00:00:01',
                'created_at' => '2019-07-16 00:00:01',
            ),
            58 => 
            array (
                'id' => 71,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 39,
                'admin_name' => 'lingtest',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+90000|[目前额度]=>>90000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-16 00:00:02',
                'created_at' => '2019-07-16 00:00:02',
            ),
            59 => 
            array (
                'id' => 72,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 40,
                'admin_name' => 'ling2',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+90000|[目前额度]=>>90000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-16 00:00:02',
                'created_at' => '2019-07-16 00:00:02',
            ),
            60 => 
            array (
                'id' => 73,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 41,
                'admin_name' => 'ling3',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+90000|[目前额度]=>>90000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-16 00:00:02',
                'created_at' => '2019-07-16 00:00:02',
            ),
            61 => 
            array (
                'id' => 74,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 23,
                'super_admin_name' => 'Diana',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'amount' => '110.00',
                'comment' => '[给用户人工充值]==>-110|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-19 14:44:38',
                'created_at' => '2019-07-19 14:44:38',
            ),
            62 => 
            array (
                'id' => 75,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 23,
                'super_admin_name' => 'Diana',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 14,
                'user_name' => 'diana111',
                'amount' => '1000.00',
                'comment' => '[给用户人工充值]==>-1000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-19 14:45:35',
                'created_at' => '2019-07-19 14:45:35',
            ),
            63 => 
            array (
                'id' => 76,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 23,
                'super_admin_name' => 'Diana',
                'admin_id' => 34,
                'admin_name' => 'diana111',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '5000.00',
                'comment' => '[人工充值额度操作]==>+5000|[目前额度]==>95000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-19 15:23:16',
                'created_at' => '2019-07-19 15:23:16',
            ),
            64 => 
            array (
                'id' => 77,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 37,
                'admin_name' => 'max2',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+90000|[目前额度]=>>90000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-25 00:00:01',
                'created_at' => '2019-07-25 00:00:01',
            ),
            65 => 
            array (
                'id' => 78,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 37,
                'admin_name' => 'max2',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+90000|[目前额度]=>>90000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-25 00:00:02',
                'created_at' => '2019-07-25 00:00:02',
            ),
            66 => 
            array (
                'id' => 79,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 24,
                'super_admin_name' => 'Ling',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 16,
                'user_name' => 'ling1',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-07-29 21:26:44',
                'created_at' => '2019-07-29 21:26:44',
            ),
            67 => 
            array (
                'id' => 80,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 3,
                'user_name' => 'kiki',
                'amount' => '100.00',
                'comment' => '[给用户人工充值]==>-100|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-07 15:58:28',
                'created_at' => '2019-08-07 15:58:28',
            ),
            68 => 
            array (
                'id' => 81,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 24,
                'super_admin_name' => 'Ling',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 21,
                'user_name' => 'jeff',
                'amount' => '5000.00',
                'comment' => '[给用户人工充值]==>-5000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-07 16:46:40',
                'created_at' => '2019-08-07 16:46:40',
            ),
            69 => 
            array (
                'id' => 82,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 3,
                'user_name' => 'kiki',
                'amount' => '100.00',
                'comment' => '[给用户人工充值]==>-100|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-07 16:59:40',
                'created_at' => '2019-08-07 16:59:40',
            ),
            70 => 
            array (
                'id' => 83,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 24,
                'super_admin_name' => 'Ling',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 21,
                'user_name' => 'jeff',
                'amount' => '5000.00',
                'comment' => '[给用户人工充值]==>-5000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-07 17:02:07',
                'created_at' => '2019-08-07 17:02:07',
            ),
            71 => 
            array (
                'id' => 84,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 24,
                'super_admin_name' => 'Ling',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 21,
                'user_name' => 'jeff',
                'amount' => '3000.00',
                'comment' => '[给用户人工充值]==>-3000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-07 17:02:46',
                'created_at' => '2019-08-07 17:02:46',
            ),
            72 => 
            array (
                'id' => 85,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 24,
                'super_admin_name' => 'Ling',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 21,
                'user_name' => 'jeff',
                'amount' => '222.00',
                'comment' => '[给用户人工充值]==>-222|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-07 17:03:28',
                'created_at' => '2019-08-07 17:03:28',
            ),
            73 => 
            array (
                'id' => 86,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 24,
                'super_admin_name' => 'Ling',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 21,
                'user_name' => 'jeff',
                'amount' => '2000.00',
                'comment' => '[给用户人工充值]==>-2000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-07 17:03:59',
                'created_at' => '2019-08-07 17:03:59',
            ),
            74 => 
            array (
                'id' => 87,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 21,
                'user_name' => 'jeff',
                'amount' => '20.00',
                'comment' => '[给用户人工充值]==>-20|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-07 17:05:19',
                'created_at' => '2019-08-07 17:05:19',
            ),
            75 => 
            array (
                'id' => 88,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 3,
                'user_name' => 'kiki',
                'amount' => '100.00',
                'comment' => '[给用户人工充值]==>-100|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-07 18:04:25',
                'created_at' => '2019-08-07 18:04:25',
            ),
            76 => 
            array (
                'id' => 89,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 3,
                'user_name' => 'kiki',
                'amount' => '100.00',
                'comment' => '[给用户人工充值]==>-100|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-08 14:16:33',
                'created_at' => '2019-08-08 14:16:33',
            ),
            77 => 
            array (
                'id' => 90,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 3,
                'user_name' => 'kiki',
                'amount' => '100.00',
                'comment' => '[给用户人工充值]==>-100|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-08 14:17:13',
                'created_at' => '2019-08-08 14:17:13',
            ),
            78 => 
            array (
                'id' => 91,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'amount' => '100.00',
                'comment' => '[给用户人工充值]==>-100|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-08 14:18:18',
                'created_at' => '2019-08-08 14:18:18',
            ),
            79 => 
            array (
                'id' => 92,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'amount' => '100.00',
                'comment' => '[给用户人工充值]==>-100|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-08 14:18:45',
                'created_at' => '2019-08-08 14:18:45',
            ),
            80 => 
            array (
                'id' => 93,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'amount' => '100.00',
                'comment' => '[给用户人工充值]==>-100|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-08 14:19:00',
                'created_at' => '2019-08-08 14:19:00',
            ),
            81 => 
            array (
                'id' => 94,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'amount' => '100.00',
                'comment' => '[给用户人工充值]==>-100|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-08 14:20:06',
                'created_at' => '2019-08-08 14:20:06',
            ),
            82 => 
            array (
                'id' => 95,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 22,
                'user_name' => 'max777',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-14 17:58:55',
                'created_at' => '2019-08-14 17:58:55',
            ),
            83 => 
            array (
                'id' => 96,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 22,
                'user_name' => 'max777',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-14 17:59:32',
                'created_at' => '2019-08-14 17:59:32',
            ),
            84 => 
            array (
                'id' => 97,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 29,
                'super_admin_name' => 'young',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 26,
                'user_name' => 'Ida',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-15 14:13:10',
                'created_at' => '2019-08-15 14:13:10',
            ),
            85 => 
            array (
                'id' => 98,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 29,
                'super_admin_name' => 'young',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 26,
                'user_name' => 'Ida',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-15 14:13:21',
                'created_at' => '2019-08-15 14:13:21',
            ),
            86 => 
            array (
                'id' => 99,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 28,
                'super_admin_name' => 'kitty',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 29,
                'user_name' => 'kittyts',
                'amount' => '10000.00',
                'comment' => '[给用户人工充值]==>-10000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-16 10:19:28',
                'created_at' => '2019-08-16 10:19:28',
            ),
            87 => 
            array (
                'id' => 100,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 28,
                'super_admin_name' => 'kitty',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 13,
                'user_name' => 'Kitty',
                'amount' => '1000.00',
                'comment' => '[给用户人工充值]==>-1000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-16 10:21:37',
                'created_at' => '2019-08-16 10:21:37',
            ),
            88 => 
            array (
                'id' => 101,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 4,
                'super_admin_name' => 'york',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 16,
                'user_name' => 'ling1',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-16 21:25:25',
                'created_at' => '2019-08-16 21:25:25',
            ),
            89 => 
            array (
                'id' => 102,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 51,
                'super_admin_name' => 'samuel',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 36,
                'user_name' => 'alan888',
                'amount' => '50000.00',
                'comment' => '[给用户人工充值]==>-50000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-18 01:14:43',
                'created_at' => '2019-08-18 01:14:43',
            ),
            90 => 
            array (
                'id' => 103,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 53,
                'super_admin_name' => 'demi',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 66,
                'user_name' => 'jaxton',
                'amount' => '50000.00',
                'comment' => '[给用户人工充值]==>-50000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-18 01:29:26',
                'created_at' => '2019-08-18 01:29:26',
            ),
            91 => 
            array (
                'id' => 104,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 53,
                'super_admin_name' => 'demi',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 66,
                'user_name' => 'jaxton',
                'amount' => '2000.00',
                'comment' => '[给用户人工充值]==>-2000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-18 03:00:11',
                'created_at' => '2019-08-18 03:00:11',
            ),
            92 => 
            array (
                'id' => 105,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 53,
                'super_admin_name' => 'demi',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 66,
                'user_name' => 'jaxton',
                'amount' => '2500.00',
                'comment' => '[给用户人工充值]==>-2500|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-18 03:04:59',
                'created_at' => '2019-08-18 03:04:59',
            ),
            93 => 
            array (
                'id' => 106,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 53,
                'super_admin_name' => 'demi',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 66,
                'user_name' => 'jaxton',
                'amount' => '500.00',
                'comment' => '[给用户人工充值]==>-500|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-18 03:07:18',
                'created_at' => '2019-08-18 03:07:18',
            ),
            94 => 
            array (
                'id' => 107,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 53,
                'super_admin_name' => 'demi',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 66,
                'user_name' => 'jaxton',
                'amount' => '5000.00',
                'comment' => '[给用户人工充值]==>-5000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-18 03:08:07',
                'created_at' => '2019-08-18 03:08:07',
            ),
            95 => 
            array (
                'id' => 108,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 81,
                'user_name' => 'max7777',
                'amount' => '50000.00',
                'comment' => '[给用户人工充值]==>-50000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-30 16:37:40',
                'created_at' => '2019-08-30 16:37:40',
            ),
            96 => 
            array (
                'id' => 109,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 82,
                'user_name' => 'max77777',
                'amount' => '50000.00',
                'comment' => '[给用户人工充值]==>-50000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-30 16:41:49',
                'created_at' => '2019-08-30 16:41:49',
            ),
            97 => 
            array (
                'id' => 110,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 83,
                'user_name' => 'max886',
                'amount' => '5000.00',
                'comment' => '[给用户人工充值]==>-5000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-30 17:23:24',
                'created_at' => '2019-08-30 17:23:24',
            ),
            98 => 
            array (
                'id' => 111,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 43,
                'super_admin_name' => 'max1111',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 84,
                'user_name' => 'max789',
                'amount' => '1234.00',
                'comment' => '[给用户人工充值]==>-1234|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-30 17:26:15',
                'created_at' => '2019-08-30 17:26:15',
            ),
            99 => 
            array (
                'id' => 112,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 55,
                'super_admin_name' => 'bayern',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 96,
                'user_name' => 'bayern',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-31 10:42:14',
                'created_at' => '2019-08-31 10:42:14',
            ),
            100 => 
            array (
                'id' => 113,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 55,
                'super_admin_name' => 'bayern',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 97,
                'user_name' => 'zxc',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-31 11:26:40',
                'created_at' => '2019-08-31 11:26:40',
            ),
            101 => 
            array (
                'id' => 114,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 55,
                'super_admin_name' => 'bayern',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 97,
                'user_name' => 'zxc',
                'amount' => '18000.00',
                'comment' => '[给用户人工充值]==>-18000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-31 17:41:08',
                'created_at' => '2019-08-31 17:41:08',
            ),
            102 => 
            array (
                'id' => 115,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 55,
                'super_admin_name' => 'bayern',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 97,
                'user_name' => 'zxc',
                'amount' => '18000.00',
                'comment' => '[给用户人工充值]==>-18000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-31 17:52:55',
                'created_at' => '2019-08-31 17:52:55',
            ),
            103 => 
            array (
                'id' => 116,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 55,
                'super_admin_name' => 'bayern',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 97,
                'user_name' => 'zxc',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-31 18:08:17',
                'created_at' => '2019-08-31 18:08:17',
            ),
            104 => 
            array (
                'id' => 117,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 55,
                'super_admin_name' => 'bayern',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 97,
                'user_name' => 'zxc',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-31 18:08:31',
                'created_at' => '2019-08-31 18:08:31',
            ),
            105 => 
            array (
                'id' => 118,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 55,
                'super_admin_name' => 'bayern',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 97,
                'user_name' => 'zxc',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-31 18:08:37',
                'created_at' => '2019-08-31 18:08:37',
            ),
            106 => 
            array (
                'id' => 119,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 55,
                'super_admin_name' => 'bayern',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 97,
                'user_name' => 'zxc',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-31 18:08:43',
                'created_at' => '2019-08-31 18:08:43',
            ),
            107 => 
            array (
                'id' => 120,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 55,
                'super_admin_name' => 'bayern',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 97,
                'user_name' => 'zxc',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-31 18:08:52',
                'created_at' => '2019-08-31 18:08:52',
            ),
            108 => 
            array (
                'id' => 121,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 55,
                'super_admin_name' => 'bayern',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 97,
                'user_name' => 'zxc',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-31 18:08:57',
                'created_at' => '2019-08-31 18:08:57',
            ),
            109 => 
            array (
                'id' => 122,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 55,
                'super_admin_name' => 'bayern',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 97,
                'user_name' => 'zxc',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-08-31 18:09:06',
                'created_at' => '2019-08-31 18:09:06',
            ),
            110 => 
            array (
                'id' => 123,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 55,
                'super_admin_name' => 'bayern',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 97,
                'user_name' => 'zxc',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-09-02 14:23:24',
                'created_at' => '2019-09-02 14:23:24',
            ),
            111 => 
            array (
                'id' => 124,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 55,
                'super_admin_name' => 'bayern',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 81,
                'user_name' => 'max7777',
                'amount' => '90000.00',
                'comment' => '[给用户人工充值]==>-90000|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'recharge_id' => NULL,
                'updated_at' => '2019-09-03 15:29:46',
                'created_at' => '2019-09-03 15:29:46',
            ),
        ));
        
        
    }
}