<?php

use Illuminate\Database\Seeder;

class FrontendUsersSpecificInfosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('frontend_users_specific_infos')->delete();
        
        \DB::table('frontend_users_specific_infos')->insert(array (
            0 => 
            array (
                'id' => 1,
                'nickname' => '蛤蛤',
                'realname' => '1233',
                'mobile' => '13880628809',
                'email' => '1823444@qq.com',
                'zip_code' => '233333',
                'address' => '朝歌',
                'register_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2019-08-28 15:46:01',
                'total_members' => 6,
                'user_id' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'total_members' => 0,
                'user_id' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 4,
            ),
            4 => 
            array (
                'id' => 5,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => NULL,
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 5,
            ),
            5 => 
            array (
                'id' => 11,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-15 17:23:18',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 31,
            ),
            6 => 
            array (
                'id' => 12,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 2,
                'created_at' => '2019-08-15 20:11:33',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 32,
            ),
            7 => 
            array (
                'id' => 13,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-15 20:29:56',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 33,
            ),
            8 => 
            array (
                'id' => 14,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 2,
                'created_at' => '2019-08-15 20:51:05',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 35,
            ),
            9 => 
            array (
                'id' => 15,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-15 22:00:34',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 37,
            ),
            10 => 
            array (
                'id' => 16,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-15 22:25:51',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 38,
            ),
            11 => 
            array (
                'id' => 17,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-16 03:10:43',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 39,
            ),
            12 => 
            array (
                'id' => 18,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-16 05:28:33',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 40,
            ),
            13 => 
            array (
                'id' => 19,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-16 11:03:03',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 41,
            ),
            14 => 
            array (
                'id' => 20,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 2,
                'created_at' => '2019-08-16 11:09:17',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 42,
            ),
            15 => 
            array (
                'id' => 21,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-16 12:44:05',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 43,
            ),
            16 => 
            array (
                'id' => 22,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 2,
                'created_at' => '2019-08-16 12:44:24',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 44,
            ),
            17 => 
            array (
                'id' => 23,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-16 12:47:51',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 45,
            ),
            18 => 
            array (
                'id' => 24,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-16 15:54:24',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 46,
            ),
            19 => 
            array (
                'id' => 25,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-16 16:22:06',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 47,
            ),
            20 => 
            array (
                'id' => 26,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 2,
                'created_at' => '2019-08-16 16:25:25',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 48,
            ),
            21 => 
            array (
                'id' => 27,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-16 16:25:26',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 49,
            ),
            22 => 
            array (
                'id' => 28,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-16 16:26:12',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 50,
            ),
            23 => 
            array (
                'id' => 29,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 2,
                'created_at' => '2019-08-16 16:27:35',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 51,
            ),
            24 => 
            array (
                'id' => 30,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-16 16:27:54',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 52,
            ),
            25 => 
            array (
                'id' => 31,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-16 16:40:34',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 53,
            ),
            26 => 
            array (
                'id' => 32,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-16 16:42:26',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 54,
            ),
            27 => 
            array (
                'id' => 33,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 2,
                'created_at' => '2019-08-16 21:25:28',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 55,
            ),
            28 => 
            array (
                'id' => 34,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-16 21:26:51',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 56,
            ),
            29 => 
            array (
                'id' => 35,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-16 21:29:04',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 57,
            ),
            30 => 
            array (
                'id' => 36,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 2,
                'created_at' => '2019-08-16 21:30:23',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 58,
            ),
            31 => 
            array (
                'id' => 37,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-17 16:38:07',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 59,
            ),
            32 => 
            array (
                'id' => 38,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-17 16:38:42',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 60,
            ),
            33 => 
            array (
                'id' => 39,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 17:18:07',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 61,
            ),
            34 => 
            array (
                'id' => 40,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 19:05:22',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 62,
            ),
            35 => 
            array (
                'id' => 41,
                'nickname' => '323',
                'realname' => '323222',
                'mobile' => '13910203322',
                'email' => 'dss212dds@qq.com',
                'zip_code' => '102323',
                'address' => '多少大蒜大 ddasd的大时代撒大蒜撒的啊撒大蒜大撒的撒的撒啊撒撒撒撒啊撒撒的的的多少大蒜请输入请输入请输入请输入请输入请输入请输入请输入请输入请输入请输入请输',
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-21 17:50:08',
                'total_members' => 9,
                'user_id' => 3,
            ),
            36 => 
            array (
                'id' => 42,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 6,
            ),
            37 => 
            array (
                'id' => 43,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 7,
            ),
            38 => 
            array (
                'id' => 44,
                'nickname' => '王八',
                'realname' => NULL,
                'mobile' => '',
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-09-02 17:48:13',
                'total_members' => 2,
                'user_id' => 8,
            ),
            39 => 
            array (
                'id' => 45,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 9,
            ),
            40 => 
            array (
                'id' => 46,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 10,
            ),
            41 => 
            array (
                'id' => 47,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 11,
            ),
            42 => 
            array (
                'id' => 48,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 12,
            ),
            43 => 
            array (
                'id' => 49,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 13,
            ),
            44 => 
            array (
                'id' => 50,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 14,
            ),
            45 => 
            array (
                'id' => 51,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 15,
            ),
            46 => 
            array (
                'id' => 52,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => 'test',
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-23 10:20:59',
                'total_members' => 0,
                'user_id' => 16,
            ),
            47 => 
            array (
                'id' => 53,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 17,
            ),
            48 => 
            array (
                'id' => 54,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 18,
            ),
            49 => 
            array (
                'id' => 55,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 19,
            ),
            50 => 
            array (
                'id' => 56,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 20,
            ),
            51 => 
            array (
                'id' => 57,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 21,
            ),
            52 => 
            array (
                'id' => 58,
                'nickname' => 'J',
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-29 10:39:53',
                'total_members' => 3,
                'user_id' => 22,
            ),
            53 => 
            array (
                'id' => 59,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 23,
            ),
            54 => 
            array (
                'id' => 60,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 24,
            ),
            55 => 
            array (
                'id' => 61,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 25,
            ),
            56 => 
            array (
                'id' => 62,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 26,
            ),
            57 => 
            array (
                'id' => 63,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 27,
            ),
            58 => 
            array (
                'id' => 64,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 28,
            ),
            59 => 
            array (
                'id' => 65,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 29,
            ),
            60 => 
            array (
                'id' => 66,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:55',
                'updated_at' => '2019-08-17 21:24:55',
                'total_members' => 0,
                'user_id' => 30,
            ),
            61 => 
            array (
                'id' => 67,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:56',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 34,
            ),
            62 => 
            array (
                'id' => 68,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-17 21:24:56',
                'updated_at' => '2019-08-17 21:24:56',
                'total_members' => 0,
                'user_id' => 36,
            ),
            63 => 
            array (
                'id' => 69,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 2,
                'created_at' => '2019-08-17 21:32:54',
                'updated_at' => '2019-08-17 21:32:54',
                'total_members' => 0,
                'user_id' => 63,
            ),
            64 => 
            array (
                'id' => 70,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 2,
                'created_at' => '2019-08-17 21:34:20',
                'updated_at' => '2019-08-17 21:34:20',
                'total_members' => 0,
                'user_id' => 64,
            ),
            65 => 
            array (
                'id' => 71,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-17 23:38:26',
                'updated_at' => '2019-08-17 23:38:26',
                'total_members' => 0,
                'user_id' => 65,
            ),
            66 => 
            array (
                'id' => 72,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-18 01:14:52',
                'updated_at' => '2019-08-18 01:14:52',
                'total_members' => 0,
                'user_id' => 66,
            ),
            67 => 
            array (
                'id' => 73,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-18 03:19:25',
                'updated_at' => '2019-08-18 03:19:25',
                'total_members' => 0,
                'user_id' => 67,
            ),
            68 => 
            array (
                'id' => 74,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-18 17:36:14',
                'updated_at' => '2019-08-18 17:36:14',
                'total_members' => 0,
                'user_id' => 68,
            ),
            69 => 
            array (
                'id' => 75,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-18 19:55:12',
                'updated_at' => '2019-08-18 19:55:12',
                'total_members' => 0,
                'user_id' => 69,
            ),
            70 => 
            array (
                'id' => 76,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-19 10:02:08',
                'updated_at' => '2019-08-19 10:02:08',
                'total_members' => 0,
                'user_id' => 70,
            ),
            71 => 
            array (
                'id' => 77,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-19 11:10:01',
                'updated_at' => '2019-08-19 11:10:01',
                'total_members' => 0,
                'user_id' => 71,
            ),
            72 => 
            array (
                'id' => 78,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-19 12:57:34',
                'updated_at' => '2019-08-19 12:57:34',
                'total_members' => 0,
                'user_id' => 72,
            ),
            73 => 
            array (
                'id' => 79,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-19 13:31:07',
                'updated_at' => '2019-08-19 13:31:07',
                'total_members' => 0,
                'user_id' => 73,
            ),
            74 => 
            array (
                'id' => 80,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-21 14:40:36',
                'updated_at' => '2019-08-21 14:40:36',
                'total_members' => 0,
                'user_id' => 74,
            ),
            75 => 
            array (
                'id' => 81,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-22 14:36:02',
                'updated_at' => '2019-08-22 14:36:02',
                'total_members' => 0,
                'user_id' => 75,
            ),
            76 => 
            array (
                'id' => 82,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-22 15:26:27',
                'updated_at' => '2019-08-22 15:26:27',
                'total_members' => 0,
                'user_id' => 76,
            ),
            77 => 
            array (
                'id' => 83,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-27 16:16:35',
                'updated_at' => '2019-08-27 16:16:35',
                'total_members' => 0,
                'user_id' => 77,
            ),
            78 => 
            array (
                'id' => 84,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-28 15:48:10',
                'updated_at' => '2019-08-28 15:48:10',
                'total_members' => 0,
                'user_id' => 78,
            ),
            79 => 
            array (
                'id' => 85,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-28 15:48:34',
                'updated_at' => '2019-08-28 15:48:34',
                'total_members' => 0,
                'user_id' => 79,
            ),
            80 => 
            array (
                'id' => 86,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-30 16:27:56',
                'updated_at' => '2019-08-30 16:27:56',
                'total_members' => 0,
                'user_id' => 80,
            ),
            81 => 
            array (
                'id' => 87,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-30 17:22:50',
                'updated_at' => '2019-08-30 17:22:50',
                'total_members' => 0,
                'user_id' => 83,
            ),
            82 => 
            array (
                'id' => 88,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-30 17:25:41',
                'updated_at' => '2019-08-30 17:25:41',
                'total_members' => 0,
                'user_id' => 84,
            ),
            83 => 
            array (
                'id' => 89,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-30 17:28:06',
                'updated_at' => '2019-08-30 17:28:06',
                'total_members' => 0,
                'user_id' => 85,
            ),
            84 => 
            array (
                'id' => 90,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-30 17:29:58',
                'updated_at' => '2019-08-30 17:29:58',
                'total_members' => 0,
                'user_id' => 86,
            ),
            85 => 
            array (
                'id' => 91,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 2,
                'created_at' => '2019-08-30 17:32:03',
                'updated_at' => '2019-08-30 17:32:03',
                'total_members' => 0,
                'user_id' => 87,
            ),
            86 => 
            array (
                'id' => 92,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 2,
                'created_at' => '2019-08-30 17:44:24',
                'updated_at' => '2019-08-30 17:44:24',
                'total_members' => 0,
                'user_id' => 88,
            ),
            87 => 
            array (
                'id' => 93,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-30 17:45:08',
                'updated_at' => '2019-08-30 17:45:08',
                'total_members' => 0,
                'user_id' => 89,
            ),
            88 => 
            array (
                'id' => 94,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-30 17:52:56',
                'updated_at' => '2019-08-30 17:52:56',
                'total_members' => 0,
                'user_id' => 90,
            ),
            89 => 
            array (
                'id' => 95,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-30 17:55:05',
                'updated_at' => '2019-08-30 17:55:05',
                'total_members' => 0,
                'user_id' => 91,
            ),
            90 => 
            array (
                'id' => 96,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-30 17:55:54',
                'updated_at' => '2019-08-30 17:55:54',
                'total_members' => 0,
                'user_id' => 92,
            ),
            91 => 
            array (
                'id' => 97,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-30 17:55:55',
                'updated_at' => '2019-08-30 17:55:55',
                'total_members' => 0,
                'user_id' => 93,
            ),
            92 => 
            array (
                'id' => 98,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-08-30 17:57:55',
                'updated_at' => '2019-08-30 17:57:55',
                'total_members' => 0,
                'user_id' => 94,
            ),
            93 => 
            array (
                'id' => 99,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-31 09:48:20',
                'updated_at' => '2019-08-31 09:48:20',
                'total_members' => 0,
                'user_id' => 95,
            ),
            94 => 
            array (
                'id' => 100,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-08-31 10:38:55',
                'updated_at' => '2019-08-31 10:38:55',
                'total_members' => 0,
                'user_id' => 96,
            ),
            95 => 
            array (
                'id' => 101,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-09-02 10:46:04',
                'updated_at' => '2019-09-02 10:46:04',
                'total_members' => 0,
                'user_id' => 98,
            ),
            96 => 
            array (
                'id' => 102,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-09-02 14:40:39',
                'updated_at' => '2019-09-02 14:40:39',
                'total_members' => 0,
                'user_id' => 99,
            ),
            97 => 
            array (
                'id' => 103,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-09-03 11:33:24',
                'updated_at' => '2019-09-03 11:33:24',
                'total_members' => 0,
                'user_id' => 102,
            ),
            98 => 
            array (
                'id' => 104,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-09-03 21:10:20',
                'updated_at' => '2019-09-03 21:10:20',
                'total_members' => 0,
                'user_id' => 103,
            ),
            99 => 
            array (
                'id' => 105,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 0,
                'created_at' => '2019-09-03 21:10:45',
                'updated_at' => '2019-09-03 21:10:45',
                'total_members' => 0,
                'user_id' => 104,
            ),
            100 => 
            array (
                'id' => 106,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-09-03 21:26:58',
                'updated_at' => '2019-09-03 21:26:58',
                'total_members' => 1,
                'user_id' => 105,
            ),
            101 => 
            array (
                'id' => 107,
                'nickname' => NULL,
                'realname' => NULL,
                'mobile' => NULL,
                'email' => NULL,
                'zip_code' => NULL,
                'address' => NULL,
                'register_type' => 1,
                'created_at' => '2019-09-03 21:27:42',
                'updated_at' => '2019-09-03 21:27:42',
                'total_members' => 0,
                'user_id' => 106,
            ),
        ));
        
        
    }
}