<?php

use Illuminate\Database\Seeder;

class FrontendUsersRegisterableLinksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('frontend_users_registerable_links')->delete();
        
        \DB::table('frontend_users_registerable_links')->insert(array (
            0 => 
            array (
                'id' => 1,
                'is_tester' => 0,
                'user_id' => 2,
                'username' => 'test888',
                'prize_group' => 1956,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '0db310ce',
                'note' => NULL,
                'channel' => '',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => 'https://chunqiucp1.com/reg/0db310ce',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2018-07-05 10:37:46',
                'updated_at' => '2018-07-05 14:30:45',
            ),
            1 => 
            array (
                'id' => 2,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '26f4dd10',
                'note' => NULL,
                'channel' => 'qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/26f4dd10',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-13 20:15:27',
                'updated_at' => '2019-08-15 00:10:20',
            ),
            2 => 
            array (
                'id' => 3,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '73b553b7',
                'note' => NULL,
                'channel' => 'qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/73b553b7',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-13 20:17:31',
                'updated_at' => '2019-08-15 00:10:06',
            ),
            3 => 
            array (
                'id' => 4,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1831,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '41de7baf',
                'note' => NULL,
                'channel' => 'qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/41de7baf',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-14 21:26:05',
                'updated_at' => '2019-08-15 00:10:47',
            ),
            4 => 
            array (
                'id' => 5,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '84c63c9f',
                'note' => NULL,
                'channel' => 'qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/84c63c9f',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-14 22:35:40',
                'updated_at' => '2019-08-15 00:11:45',
            ),
            5 => 
            array (
                'id' => 6,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1835,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '71da5340',
                'note' => NULL,
                'channel' => '11',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/71da5340',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-15 00:11:41',
                'updated_at' => '2019-08-15 14:14:23',
            ),
            6 => 
            array (
                'id' => 7,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1824,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '9695511d',
                'note' => NULL,
                'channel' => '11',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/9695511d',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-15 00:19:21',
                'updated_at' => '2019-08-15 14:14:20',
            ),
            7 => 
            array (
                'id' => 8,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 1,
                'is_agent' => 1,
                'keyword' => '57d773e2',
                'note' => NULL,
                'channel' => 'face',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/57d773e2',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => '0000-00-00 00:00:00',
                'created_at' => '2019-08-15 14:16:29',
                'updated_at' => '2019-08-15 14:16:29',
            ),
            8 => 
            array (
                'id' => 9,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1811,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '96a899fc',
                'note' => NULL,
                'channel' => 'q\'qqq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/96a899fc',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-15 14:16:58',
                'updated_at' => '2019-08-27 22:18:11',
            ),
            9 => 
            array (
                'id' => 10,
                'is_tester' => 0,
                'user_id' => 22,
                'username' => 'max777',
                'prize_group' => 1945,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '6222036b',
                'note' => NULL,
                'channel' => 'QQ',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/6222036b',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-15 16:28:50',
                'updated_at' => '2019-08-15 20:04:02',
            ),
            10 => 
            array (
                'id' => 11,
                'is_tester' => 0,
                'user_id' => 22,
                'username' => 'max777',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '12bac64a',
                'note' => NULL,
                'channel' => 'qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/12bac64a',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-15 17:50:51',
                'updated_at' => '2019-08-15 20:04:03',
            ),
            11 => 
            array (
                'id' => 12,
                'is_tester' => 0,
                'user_id' => 22,
                'username' => 'max777',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '87d3aefe',
                'note' => NULL,
                'channel' => 'qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/87d3aefe',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-15 17:51:57',
                'updated_at' => '2019-08-15 20:04:04',
            ),
            12 => 
            array (
                'id' => 13,
                'is_tester' => 0,
                'user_id' => 22,
                'username' => 'max777',
                'prize_group' => 1828,
                'type' => 0,
                'valid_days' => 30,
                'is_agent' => 1,
                'keyword' => '9676e6a4',
                'note' => NULL,
                'channel' => '132',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/9676e6a4',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => '0000-00-00 00:00:00',
                'created_at' => '2019-08-15 20:08:07',
                'updated_at' => '2019-08-15 20:08:07',
            ),
            13 => 
            array (
                'id' => 14,
                'is_tester' => 0,
                'user_id' => 22,
                'username' => 'max777',
                'prize_group' => 1807,
                'type' => 0,
                'valid_days' => 30,
                'is_agent' => 1,
                'keyword' => '55e8f6bf',
                'note' => NULL,
                'channel' => '345',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/55e8f6bf',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => '0000-00-00 00:00:00',
                'created_at' => '2019-08-15 20:08:30',
                'updated_at' => '2019-08-15 20:08:30',
            ),
            14 => 
            array (
                'id' => 15,
                'is_tester' => 0,
                'user_id' => 34,
                'username' => 'three',
                'prize_group' => 1827,
                'type' => 0,
                'valid_days' => 7,
                'is_agent' => 0,
                'keyword' => '99724117',
                'note' => NULL,
                'channel' => '123456',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/99724117',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => '0000-00-00 00:00:00',
                'created_at' => '2019-08-15 20:43:03',
                'updated_at' => '2019-08-15 20:43:03',
            ),
            15 => 
            array (
                'id' => 16,
                'is_tester' => 0,
                'user_id' => 34,
                'username' => 'three',
                'prize_group' => 1827,
                'type' => 0,
                'valid_days' => 7,
                'is_agent' => 0,
                'keyword' => '9636425c',
                'note' => NULL,
                'channel' => '1234567',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/9636425c',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => '0000-00-00 00:00:00',
                'created_at' => '2019-08-15 20:43:15',
                'updated_at' => '2019-08-15 20:43:15',
            ),
            16 => 
            array (
                'id' => 17,
                'is_tester' => 0,
                'user_id' => 34,
                'username' => 'three',
                'prize_group' => 1827,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 0,
                'keyword' => '26da8ad7',
                'note' => NULL,
                'channel' => '123',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/26da8ad7',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-15 20:50:37',
                'updated_at' => '2019-08-15 20:50:37',
            ),
            17 => 
            array (
                'id' => 18,
                'is_tester' => 0,
                'user_id' => 26,
                'username' => 'Ida',
                'prize_group' => 1848,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 0,
                'keyword' => '67b2ada3',
                'note' => NULL,
                'channel' => 'QQ推广',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/67b2ada3',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-16 04:56:27',
                'updated_at' => '2019-08-16 04:56:27',
            ),
            18 => 
            array (
                'id' => 19,
                'is_tester' => 0,
                'user_id' => 26,
                'username' => 'Ida',
                'prize_group' => 1900,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 0,
                'keyword' => '65e3d37f',
                'note' => NULL,
                'channel' => 'QQ推广',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/65e3d37f',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-16 11:15:58',
                'updated_at' => '2019-08-16 11:15:58',
            ),
            19 => 
            array (
                'id' => 20,
                'is_tester' => 0,
                'user_id' => 22,
                'username' => 'max777',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 0,
                'keyword' => '18b5f5d6',
                'note' => NULL,
                'channel' => 'qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/18b5f5d6',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-16 12:44:11',
                'updated_at' => '2019-08-16 12:44:11',
            ),
            20 => 
            array (
                'id' => 21,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 0,
                'keyword' => '764b9134',
                'note' => NULL,
                'channel' => 'aAAS',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/764b9134',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-16 16:11:16',
                'updated_at' => '2019-08-27 22:18:17',
            ),
            21 => 
            array (
                'id' => 22,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '576452e0',
                'note' => NULL,
                'channel' => 'aAAS',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/576452e0',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-16 16:11:50',
                'updated_at' => '2019-08-16 16:16:49',
            ),
            22 => 
            array (
                'id' => 23,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 0,
                'keyword' => '34a45127',
                'note' => NULL,
                'channel' => 'aAAS',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/34a45127',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-16 16:16:26',
                'updated_at' => '2019-08-16 16:16:48',
            ),
            23 => 
            array (
                'id' => 24,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '70405b5f',
                'note' => NULL,
                'channel' => 'aAAS',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/70405b5f',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-16 16:16:36',
                'updated_at' => '2019-08-16 16:16:46',
            ),
            24 => 
            array (
                'id' => 25,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 0,
                'keyword' => '733304fe',
                'note' => NULL,
                'channel' => '32',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/733304fe',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-17 16:52:51',
                'updated_at' => '2019-08-31 11:21:57',
            ),
            25 => 
            array (
                'id' => 26,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 90,
                'is_agent' => 0,
                'keyword' => '75c1234c',
                'note' => NULL,
                'channel' => '32',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/75c1234c',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => '2019-11-15 16:53:16',
                'created_at' => '2019-08-17 16:53:16',
                'updated_at' => '2019-08-31 11:15:56',
            ),
            26 => 
            array (
                'id' => 27,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1865,
                'type' => 0,
                'valid_days' => 30,
                'is_agent' => 0,
                'keyword' => '35b2c110',
                'note' => NULL,
                'channel' => 'qq退关',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/35b2c110',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => '2019-09-16 18:07:07',
                'created_at' => '2019-08-17 18:07:07',
                'updated_at' => '2019-08-17 18:07:07',
            ),
            27 => 
            array (
                'id' => 28,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1891,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '66c8325e',
                'note' => NULL,
                'channel' => '11',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/66c8325e',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-17 19:07:56',
                'updated_at' => '2019-08-17 19:07:56',
            ),
            28 => 
            array (
                'id' => 29,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1900,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 0,
                'keyword' => '82138718',
                'note' => NULL,
                'channel' => 'test',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/82138718',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-17 21:32:17',
                'updated_at' => '2019-08-17 21:32:17',
            ),
            29 => 
            array (
                'id' => 30,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1900,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 0,
                'keyword' => '16fd0af8',
                'note' => NULL,
                'channel' => 'test',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/16fd0af8',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-17 21:34:07',
                'updated_at' => '2019-08-17 21:34:07',
            ),
            30 => 
            array (
                'id' => 31,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1841,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '79862e99',
                'note' => NULL,
                'channel' => 'Bhdhhs',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/79862e99',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-18 17:34:16',
                'updated_at' => '2019-08-18 17:34:16',
            ),
            31 => 
            array (
                'id' => 32,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1841,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '851e7954',
                'note' => NULL,
                'channel' => '...’',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/851e7954',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-18 17:34:57',
                'updated_at' => '2019-08-18 17:34:57',
            ),
            32 => 
            array (
                'id' => 33,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1849,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '95b1fb7e',
                'note' => NULL,
                'channel' => '232',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/95b1fb7e',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-18 19:55:23',
                'updated_at' => '2019-08-18 19:55:23',
            ),
            33 => 
            array (
                'id' => 34,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1865,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '33c48949',
                'note' => NULL,
                'channel' => 'Qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/33c48949',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-19 12:41:32',
                'updated_at' => '2019-08-31 11:20:36',
            ),
            34 => 
            array (
                'id' => 35,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1865,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '78c491d1',
                'note' => NULL,
                'channel' => 'Qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/78c491d1',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-19 12:41:32',
                'updated_at' => '2019-08-19 12:41:32',
            ),
            35 => 
            array (
                'id' => 36,
                'is_tester' => 0,
                'user_id' => 22,
                'username' => 'max777',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '5647571d',
                'note' => NULL,
                'channel' => 'qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/5647571d',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-21 13:13:24',
                'updated_at' => '2019-08-21 13:13:24',
            ),
            36 => 
            array (
                'id' => 37,
                'is_tester' => 0,
                'user_id' => 22,
                'username' => 'max777',
                'prize_group' => 1960,
                'type' => 0,
                'valid_days' => 1,
                'is_agent' => 1,
                'keyword' => '53e81885',
                'note' => NULL,
                'channel' => 'qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/53e81885',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => '2019-08-22 17:57:34',
                'created_at' => '2019-08-21 17:57:34',
                'updated_at' => '2019-08-21 17:57:34',
            ),
            37 => 
            array (
                'id' => 38,
                'is_tester' => 0,
                'user_id' => 22,
                'username' => 'max777',
                'prize_group' => 1940,
                'type' => 0,
                'valid_days' => 90,
                'is_agent' => 0,
                'keyword' => '89a5910f',
                'note' => NULL,
                'channel' => 'q\'qqq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/89a5910f',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => '2019-11-19 17:59:38',
                'created_at' => '2019-08-21 17:59:38',
                'updated_at' => '2019-08-21 17:59:38',
            ),
            38 => 
            array (
                'id' => 39,
                'is_tester' => 0,
                'user_id' => 8,
                'username' => 'young',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '48b7783a',
                'note' => NULL,
                'channel' => 'QQ',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/48b7783a',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-22 14:34:51',
                'updated_at' => '2019-08-28 17:26:34',
            ),
            39 => 
            array (
                'id' => 40,
                'is_tester' => 0,
                'user_id' => 22,
                'username' => 'max777',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '1481473f',
                'note' => NULL,
                'channel' => 'qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/1481473f',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-22 14:37:28',
                'updated_at' => '2019-08-22 14:37:28',
            ),
            40 => 
            array (
                'id' => 41,
                'is_tester' => 0,
                'user_id' => 8,
                'username' => 'young',
                'prize_group' => 1900,
                'type' => 0,
                'valid_days' => 1,
                'is_agent' => 0,
                'keyword' => '628e50b7',
                'note' => NULL,
                'channel' => '往年',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/628e50b7',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => '2019-08-23 15:43:04',
                'created_at' => '2019-08-22 15:43:04',
                'updated_at' => '2019-08-28 17:26:33',
            ),
            41 => 
            array (
                'id' => 42,
                'is_tester' => 0,
                'user_id' => 8,
                'username' => 'young',
                'prize_group' => 1900,
                'type' => 0,
                'valid_days' => 90,
                'is_agent' => 0,
                'keyword' => '44b37dae',
                'note' => NULL,
                'channel' => '往年',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/44b37dae',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => '2019-11-20 15:43:23',
                'created_at' => '2019-08-22 15:43:23',
                'updated_at' => '2019-08-28 17:26:31',
            ),
            42 => 
            array (
                'id' => 43,
                'is_tester' => 0,
                'user_id' => 8,
                'username' => 'young',
                'prize_group' => 1950,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 0,
                'keyword' => '38a6b13b',
                'note' => NULL,
                'channel' => '往年',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/38a6b13b',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-22 15:43:38',
                'updated_at' => '2019-08-28 17:26:35',
            ),
            43 => 
            array (
                'id' => 44,
                'is_tester' => 0,
                'user_id' => 8,
                'username' => 'young',
                'prize_group' => 1950,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 0,
                'keyword' => '8180c7fa',
                'note' => NULL,
                'channel' => '往年',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/8180c7fa',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-22 15:43:52',
                'updated_at' => '2019-08-28 17:26:37',
            ),
            44 => 
            array (
                'id' => 45,
                'is_tester' => 0,
                'user_id' => 8,
                'username' => 'young',
                'prize_group' => 1950,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '198898de',
                'note' => NULL,
                'channel' => '往年好',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/198898de',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => NULL,
                'created_at' => '2019-08-22 15:44:08',
                'updated_at' => '2019-08-28 17:26:40',
            ),
            45 => 
            array (
                'id' => 46,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '1259c130',
                'note' => NULL,
                'channel' => '222',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/1259c130',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-22 17:24:53',
                'updated_at' => '2019-08-22 17:24:53',
            ),
            46 => 
            array (
                'id' => 47,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 1,
                'is_agent' => 1,
                'keyword' => '51a9edd1',
                'note' => NULL,
                'channel' => '222',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/51a9edd1',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 0,
                'expired_at' => '2019-08-23 17:25:14',
                'created_at' => '2019-08-22 17:25:14',
                'updated_at' => '2019-08-31 11:21:46',
            ),
            47 => 
            array (
                'id' => 48,
                'is_tester' => 0,
                'user_id' => 22,
                'username' => 'max777',
                'prize_group' => 1881,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 0,
                'keyword' => '645b8da4',
                'note' => NULL,
                'channel' => 'q\'q',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/645b8da4',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-30 17:44:05',
                'updated_at' => '2019-08-30 17:44:05',
            ),
            48 => 
            array (
                'id' => 49,
                'is_tester' => 0,
                'user_id' => 81,
                'username' => 'max7777',
                'prize_group' => 1980,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '28eef51e',
                'note' => NULL,
                'channel' => 'q q',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/28eef51e',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-31 09:42:38',
                'updated_at' => '2019-08-31 09:42:38',
            ),
            49 => 
            array (
                'id' => 50,
                'is_tester' => 0,
                'user_id' => 81,
                'username' => 'max7777',
                'prize_group' => 1980,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '49fb2e39',
                'note' => NULL,
                'channel' => 'qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/49fb2e39',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-31 09:43:11',
                'updated_at' => '2019-08-31 09:43:11',
            ),
            50 => 
            array (
                'id' => 51,
                'is_tester' => 0,
                'user_id' => 81,
                'username' => 'max7777',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '479cabd9',
                'note' => NULL,
                'channel' => 'qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/479cabd9',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-31 10:39:37',
                'updated_at' => '2019-08-31 10:39:37',
            ),
            51 => 
            array (
                'id' => 52,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1894,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '1163e7b1',
                'note' => NULL,
                'channel' => '123',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/1163e7b1',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-31 11:25:10',
                'updated_at' => '2019-08-31 11:25:10',
            ),
            52 => 
            array (
                'id' => 53,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1894,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '92e5cd0b',
                'note' => NULL,
                'channel' => '123',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/92e5cd0b',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-31 11:25:18',
                'updated_at' => '2019-08-31 11:25:18',
            ),
            53 => 
            array (
                'id' => 54,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1902,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '69a00c04',
                'note' => NULL,
                'channel' => '134',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/69a00c04',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-31 11:26:50',
                'updated_at' => '2019-08-31 11:26:50',
            ),
            54 => 
            array (
                'id' => 55,
                'is_tester' => 0,
                'user_id' => 3,
                'username' => 'kiki',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '64910362',
                'note' => NULL,
                'channel' => '2223',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/64910362',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-08-31 11:27:37',
                'updated_at' => '2019-08-31 11:27:37',
            ),
            55 => 
            array (
                'id' => 56,
                'is_tester' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'prize_group' => 1800,
                'type' => 0,
                'valid_days' => 30,
                'is_agent' => 0,
                'keyword' => '4623207a',
                'note' => NULL,
                'channel' => 'qq',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/4623207a',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => '2019-10-02 13:58:58',
                'created_at' => '2019-09-02 13:58:58',
                'updated_at' => '2019-09-02 13:58:58',
            ),
            56 => 
            array (
                'id' => 57,
                'is_tester' => 0,
                'user_id' => 8,
                'username' => 'young',
                'prize_group' => 1960,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '71bcddbe',
                'note' => NULL,
                'channel' => 'Qq ',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/71bcddbe',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-09-02 16:16:43',
                'updated_at' => '2019-09-02 16:16:43',
            ),
            57 => 
            array (
                'id' => 58,
                'is_tester' => 0,
                'user_id' => 8,
                'username' => 'young',
                'prize_group' => 1960,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '819a36b9',
                'note' => NULL,
                'channel' => 'Qq ',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/819a36b9',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-09-02 16:16:57',
                'updated_at' => '2019-09-02 16:16:57',
            ),
            58 => 
            array (
                'id' => 59,
                'is_tester' => 0,
                'user_id' => 8,
                'username' => 'young',
                'prize_group' => 1960,
                'type' => 0,
                'valid_days' => 0,
                'is_agent' => 1,
                'keyword' => '171691a8',
                'note' => NULL,
                'channel' => 'Qq ',
                'agent_qqs' => NULL,
                'created_count' => 0,
                'url' => '/register/171691a8',
                'platform_id' => 1,
                'platform_sign' => 'a',
                'status' => 1,
                'expired_at' => NULL,
                'created_at' => '2019-09-02 16:17:05',
                'updated_at' => '2019-09-02 16:17:05',
            ),
        ));
        
        
    }
}