<?php

use Illuminate\Database\Seeder;

class FrontendUsersBankCardsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('frontend_users_bank_cards')->delete();
        
        \DB::table('frontend_users_bank_cards')->insert(array (
            0 => 
            array (
                'id' => 3,
                'user_id' => 6,
                'parent_id' => 0,
                'top_id' => 0,
                'rid' => '6',
                'username' => 'sami',
                'bank_sign' => 'CMB',
                'bank_name' => '招商银行',
                'owner_name' => '王国',
                'card_number' => '7894561237894561',
                'province_id' => '2',
                'city_id' => '33',
                'branch' => '北京支行',
                'status' => 1,
                'created_at' => '2019-07-03 15:10:36',
                'updated_at' => '2019-07-03 15:10:36',
            ),
            1 => 
            array (
                'id' => 18,
                'user_id' => 26,
                'parent_id' => 0,
                'top_id' => 0,
                'rid' => '26',
                'username' => 'Ida',
                'bank_sign' => 'ABC',
                'bank_name' => '农业银行',
                'owner_name' => '张三',
                'card_number' => '1234567891234567890',
                'province_id' => '1',
                'city_id' => '32',
                'branch' => '北京支行',
                'status' => 1,
                'created_at' => '2019-08-16 10:51:37',
                'updated_at' => '2019-08-16 10:51:37',
            ),
            2 => 
            array (
                'id' => 19,
                'user_id' => 26,
                'parent_id' => 0,
                'top_id' => 0,
                'rid' => '26',
                'username' => 'Ida',
                'bank_sign' => 'CMB',
                'bank_name' => '招商银行',
                'owner_name' => '李四',
                'card_number' => '0000111122223333444',
                'province_id' => '2',
                'city_id' => '33',
                'branch' => '天津支行',
                'status' => 1,
                'created_at' => '2019-08-16 10:54:40',
                'updated_at' => '2019-08-16 10:54:40',
            ),
            3 => 
            array (
                'id' => 22,
                'user_id' => 3,
                'parent_id' => 0,
                'top_id' => 0,
                'rid' => '3',
                'username' => 'kiki',
                'bank_sign' => 'CMB',
                'bank_name' => '交通银行',
                'owner_name' => '嗯嗯',
                'card_number' => '6222090922299222922',
                'province_id' => '1',
                'city_id' => '32',
                'branch' => '试试',
                'status' => 1,
                'created_at' => '2019-08-22 16:52:40',
                'updated_at' => '2019-08-22 16:52:40',
            ),
            4 => 
            array (
                'id' => 23,
                'user_id' => 1,
                'parent_id' => 0,
                'top_id' => 0,
                'rid' => '1',
                'username' => 'harriszhongdai',
                'bank_sign' => 'BOCOM',
                'bank_name' => '交通银行',
                'owner_name' => '帝辛',
                'card_number' => '1234567894567856',
                'province_id' => '2',
                'city_id' => '33',
                'branch' => '北京支行',
                'status' => 1,
                'created_at' => '2019-08-29 14:35:03',
                'updated_at' => '2019-08-29 14:35:03',
            ),
            5 => 
            array (
                'id' => 24,
                'user_id' => 3,
                'parent_id' => 0,
                'top_id' => 0,
                'rid' => '3',
                'username' => 'kiki',
                'bank_sign' => 'CMB',
                'bank_name' => '招商银行',
                'owner_name' => '呃呃呃',
                'card_number' => '6222080200025201000',
                'province_id' => '1',
                'city_id' => '32',
                'branch' => '呃呃呃',
                'status' => 1,
                'created_at' => '2019-08-29 16:58:49',
                'updated_at' => '2019-08-29 16:58:49',
            ),
            6 => 
            array (
                'id' => 25,
                'user_id' => 3,
                'parent_id' => 0,
                'top_id' => 0,
                'rid' => '3',
                'username' => 'kiki',
                'bank_sign' => 'CMB',
                'bank_name' => '招商银行',
                'owner_name' => '呜呜呜',
                'card_number' => '1234567891234568000',
                'province_id' => '1',
                'city_id' => '32',
                'branch' => '呃呃呃我',
                'status' => 1,
                'created_at' => '2019-08-29 16:59:58',
                'updated_at' => '2019-08-29 16:59:58',
            ),
            7 => 
            array (
                'id' => 26,
                'user_id' => 22,
                'parent_id' => 0,
                'top_id' => 0,
                'rid' => '22',
                'username' => 'max777',
                'bank_sign' => 'CMB',
                'bank_name' => '招商银行',
                'owner_name' => '你今生',
                'card_number' => '2373733384838485000',
                'province_id' => '1',
                'city_id' => '32',
                'branch' => '北京',
                'status' => 1,
                'created_at' => '2019-08-31 09:39:05',
                'updated_at' => '2019-08-31 09:39:05',
            ),
            8 => 
            array (
                'id' => 27,
                'user_id' => 3,
                'parent_id' => 0,
                'top_id' => 0,
                'rid' => '3',
                'username' => 'kiki',
                'bank_sign' => 'CMB',
                'bank_name' => '招商银行',
                'owner_name' => '呃呃呃',
                'card_number' => '2222222222222222300',
                'province_id' => '1',
                'city_id' => '32',
                'branch' => '222',
                'status' => 1,
                'created_at' => '2019-08-31 11:39:40',
                'updated_at' => '2019-08-31 11:39:40',
            ),
            9 => 
            array (
                'id' => 28,
                'user_id' => 97,
                'parent_id' => 0,
                'top_id' => 0,
                'rid' => '97',
                'username' => 'zxc',
                'bank_sign' => 'ABC',
                'bank_name' => '农业银行',
                'owner_name' => '123',
                'card_number' => '6222600260001072444',
                'province_id' => '10',
                'city_id' => '105',
                'branch' => '123',
                'status' => 1,
                'created_at' => '2019-09-02 11:51:54',
                'updated_at' => '2019-09-02 11:51:54',
            ),
            10 => 
            array (
                'id' => 29,
                'user_id' => 8,
                'parent_id' => 0,
                'top_id' => 0,
                'rid' => '8',
                'username' => 'young',
                'bank_sign' => 'CMB',
                'bank_name' => '招商银行',
                'owner_name' => '王八',
                'card_number' => '1234567891234567',
                'province_id' => '1',
                'city_id' => '32',
                'branch' => '北京支行',
                'status' => 1,
                'created_at' => '2019-09-02 17:27:33',
                'updated_at' => '2019-09-02 17:27:33',
            ),
            11 => 
            array (
                'id' => 30,
                'user_id' => 8,
                'parent_id' => 0,
                'top_id' => 0,
                'rid' => '8',
                'username' => 'young',
                'bank_sign' => 'CMB',
                'bank_name' => '农业银行',
                'owner_name' => '王八',
                'card_number' => '1234567891234568000',
                'province_id' => '2',
                'city_id' => '33',
                'branch' => '天津支行',
                'status' => 1,
                'created_at' => '2019-09-02 17:32:02',
                'updated_at' => '2019-09-02 17:32:02',
            ),
            12 => 
            array (
                'id' => 31,
                'user_id' => 81,
                'parent_id' => 0,
                'top_id' => 0,
                'rid' => '81',
                'username' => 'max7777',
                'bank_sign' => 'CCB',
                'bank_name' => '建设银行',
                'owner_name' => '在',
                'card_number' => '6222600260001072444',
                'province_id' => '1',
                'city_id' => '32',
                'branch' => '1',
                'status' => 1,
                'created_at' => '2019-09-03 14:35:28',
                'updated_at' => '2019-09-03 14:35:28',
            ),
            13 => 
            array (
                'id' => 32,
                'user_id' => 81,
                'parent_id' => 0,
                'top_id' => 0,
                'rid' => '81',
                'username' => 'max7777',
                'bank_sign' => 'CMB',
                'bank_name' => '招商银行',
                'owner_name' => 'bayern',
                'card_number' => '6217001370027270875',
                'province_id' => '10',
                'city_id' => '105',
                'branch' => '长江路支行',
                'status' => 1,
                'created_at' => '2019-09-03 14:58:57',
                'updated_at' => '2019-09-03 14:58:57',
            ),
        ));
        
        
    }
}