<?php

use Illuminate\Database\Seeder;

class FrontendLotteryFnfBetableMethodsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('frontend_lottery_fnf_betable_methods')->delete();
        
        \DB::table('frontend_lottery_fnf_betable_methods')->insert(array (
            0 => 
            array (
                'id' => 93,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'YFFS',
                'method_name' => '一帆风顺',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            1 => 
            array (
                'id' => 94,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'HSCS',
                'method_name' => '好事成双',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            2 => 
            array (
                'id' => 95,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'SXBX',
                'method_name' => '三星报喜',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            3 => 
            array (
                'id' => 96,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'SJFC',
                'method_name' => '四季发财',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            4 => 
            array (
                'id' => 199,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'YFFS',
                'method_name' => '一帆风顺',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            5 => 
            array (
                'id' => 200,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'HSCS',
                'method_name' => '好事成双',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            6 => 
            array (
                'id' => 201,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'SXBX',
                'method_name' => '三星报喜',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            7 => 
            array (
                'id' => 202,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'SJFC',
                'method_name' => '四季发财',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            8 => 
            array (
                'id' => 305,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'YFFS',
                'method_name' => '一帆风顺',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            9 => 
            array (
                'id' => 306,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'HSCS',
                'method_name' => '好事成双',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            10 => 
            array (
                'id' => 307,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'SXBX',
                'method_name' => '三星报喜',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            11 => 
            array (
                'id' => 308,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'SJFC',
                'method_name' => '四季发财',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            12 => 
            array (
                'id' => 411,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'YFFS',
                'method_name' => '一帆风顺',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            13 => 
            array (
                'id' => 412,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'HSCS',
                'method_name' => '好事成双',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            14 => 
            array (
                'id' => 413,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'SXBX',
                'method_name' => '三星报喜',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            15 => 
            array (
                'id' => 414,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'SJFC',
                'method_name' => '四季发财',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            16 => 
            array (
                'id' => 517,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'YFFS',
                'method_name' => '一帆风顺',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            17 => 
            array (
                'id' => 518,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'HSCS',
                'method_name' => '好事成双',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            18 => 
            array (
                'id' => 519,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'SXBX',
                'method_name' => '三星报喜',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            19 => 
            array (
                'id' => 520,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'SJFC',
                'method_name' => '四季发财',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
        ));
        
        
    }
}