<?php

use Illuminate\Database\Seeder;

class UsersRechargeHistoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users_recharge_histories')->delete();
        
        \DB::table('users_recharge_histories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => NULL,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '10.000',
                'company_order_num' => '201905234541624478fd78a4d',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => 257,
                'status' => 12,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-05-23 17:45:10',
                'created_at' => '2019-05-23 17:42:21',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => NULL,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '10.000',
                'company_order_num' => '20190525928480329084bf16c',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => 258,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-05-25 15:28:44',
                'created_at' => '2019-05-25 15:28:04',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '1.000',
                'company_order_num' => '2019060644115278420b36186',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-06-06 17:46:51',
                'created_at' => '2019-06-06 17:46:51',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 3,
                'user_name' => 'kiki',
                'is_tester' => 0,
                'top_agent' => NULL,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '10000.000',
                'company_order_num' => '2019070195114659779645474',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-01 19:11:51',
                'created_at' => '2019-07-01 19:11:51',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 4,
                'user_name' => 'york34',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '1000.000',
                'company_order_num' => '2019070371519156437795805',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-03 12:12:31',
                'created_at' => '2019-07-03 12:12:31',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 4,
                'user_name' => 'york34',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '10000.000',
                'company_order_num' => '2019070371739985886476133',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-03 12:12:53',
                'created_at' => '2019-07-03 12:12:53',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 4,
                'user_name' => 'york34',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '10000.000',
                'company_order_num' => '2019070583183221992417121',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-05 14:31:58',
                'created_at' => '2019-07-05 14:31:58',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 4,
                'user_name' => 'york34',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '80000.000',
                'company_order_num' => '2019070583399506437658592',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-05 14:32:19',
                'created_at' => '2019-07-05 14:32:19',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 8,
                'user_name' => 'young',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => '2019070897794595024292027',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-08 15:09:39',
                'created_at' => '2019-07-08 15:09:39',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 8,
                'user_name' => 'young',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => '2019070897898041828455279',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-08 15:09:49',
                'created_at' => '2019-07-08 15:09:49',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 8,
                'user_name' => 'young',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => '2019070897991925714058599',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-08 15:09:59',
                'created_at' => '2019-07-08 15:09:59',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 8,
                'user_name' => 'young',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => '2019070898125845943001489',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-08 15:10:12',
                'created_at' => '2019-07-08 15:10:12',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 14,
                'user_name' => 'diana111',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '1000.000',
                'company_order_num' => '2019071537592954624002910',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-15 14:55:59',
                'created_at' => '2019-07-15 14:55:59',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '10.000',
                'company_order_num' => '2019071551616327323080787',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-15 15:19:21',
                'created_at' => '2019-07-15 15:19:21',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 14,
                'user_name' => 'diana111',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '10.000',
                'company_order_num' => '2019071551916698764336501',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-15 15:19:51',
                'created_at' => '2019-07-15 15:19:51',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '110.000',
                'company_order_num' => '2019071986783871496792848',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-19 14:44:38',
                'created_at' => '2019-07-19 14:44:38',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 14,
                'user_name' => 'diana111',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '1000.000',
                'company_order_num' => '2019071987359702788968976',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-19 14:45:35',
                'created_at' => '2019-07-19 14:45:35',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 16,
                'user_name' => 'ling1',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => '2019072968042926885896592',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-07-29 21:26:44',
                'created_at' => '2019-07-29 21:26:44',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 3,
                'user_name' => 'kiki',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '100.000',
                'company_order_num' => '2019080747087984906435605',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-07 15:58:28',
                'created_at' => '2019-08-07 15:58:28',
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 21,
                'user_name' => 'jeff',
                'is_tester' => 1,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '5000.000',
                'company_order_num' => '2019080776003934544350821',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-07 16:46:40',
                'created_at' => '2019-08-07 16:46:40',
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 3,
                'user_name' => 'kiki',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '100.000',
                'company_order_num' => '2019080783803793127673844',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-07 16:59:40',
                'created_at' => '2019-08-07 16:59:40',
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 21,
                'user_name' => 'jeff',
                'is_tester' => 1,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '5000.000',
                'company_order_num' => '2019080785272292053355849',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-07 17:02:07',
                'created_at' => '2019-08-07 17:02:07',
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 21,
                'user_name' => 'jeff',
                'is_tester' => 1,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '3000.000',
                'company_order_num' => '2019080785665777323248979',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-07 17:02:46',
                'created_at' => '2019-08-07 17:02:46',
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 21,
                'user_name' => 'jeff',
                'is_tester' => 1,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '222.000',
                'company_order_num' => '2019080786086321066274269',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-07 17:03:28',
                'created_at' => '2019-08-07 17:03:28',
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 21,
                'user_name' => 'jeff',
                'is_tester' => 1,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '2000.000',
                'company_order_num' => '2019080786395519322884662',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-07 17:03:59',
                'created_at' => '2019-08-07 17:03:59',
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 21,
                'user_name' => 'jeff',
                'is_tester' => 1,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '20.000',
                'company_order_num' => '2019080787192600068828507',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-07 17:05:19',
                'created_at' => '2019-08-07 17:05:19',
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 3,
                'user_name' => 'kiki',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '100.000',
                'company_order_num' => '2019080722653861141142008',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-07 18:04:25',
                'created_at' => '2019-08-07 18:04:25',
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 3,
                'user_name' => 'kiki',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '100.000',
                'company_order_num' => '2019080849932701672199609',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-08 14:16:33',
                'created_at' => '2019-08-08 14:16:33',
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 3,
                'user_name' => 'kiki',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '100.000',
                'company_order_num' => '2019080850335194814598606',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-08 14:17:13',
                'created_at' => '2019-08-08 14:17:13',
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '100.000',
                'company_order_num' => '2019080850981587215691842',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-08 14:18:18',
                'created_at' => '2019-08-08 14:18:18',
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '100.000',
                'company_order_num' => '2019080851256021779942090',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-08 14:18:45',
                'created_at' => '2019-08-08 14:18:45',
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '100.000',
                'company_order_num' => '2019080851406147861351414',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-08 14:19:00',
                'created_at' => '2019-08-08 14:19:00',
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '100.000',
                'company_order_num' => '2019080852066237696564723',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-08 14:20:06',
                'created_at' => '2019-08-08 14:20:06',
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 22,
                'user_name' => 'max777',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => '2019081467354315224241772',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-14 17:58:55',
                'created_at' => '2019-08-14 17:58:55',
            ),
            34 => 
            array (
                'id' => 35,
                'user_id' => 22,
                'user_name' => 'max777',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => '2019081467726356779608275',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-14 17:59:32',
                'created_at' => '2019-08-14 17:59:32',
            ),
            35 => 
            array (
                'id' => 36,
                'user_id' => 26,
                'user_name' => 'Ida',
                'is_tester' => 1,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => '2019081595903403971894114',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-15 14:13:10',
                'created_at' => '2019-08-15 14:13:10',
            ),
            36 => 
            array (
                'id' => 37,
                'user_id' => 26,
                'user_name' => 'Ida',
                'is_tester' => 1,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => '2019081596013376859425893',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-15 14:13:21',
                'created_at' => '2019-08-15 14:13:21',
            ),
            37 => 
            array (
                'id' => 38,
                'user_id' => 29,
                'user_name' => 'kittyts',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '10000.000',
                'company_order_num' => '2019081619687042512284765',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-16 10:19:28',
                'created_at' => '2019-08-16 10:19:28',
            ),
            38 => 
            array (
                'id' => 39,
                'user_id' => 13,
                'user_name' => 'Kitty',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '1000.000',
                'company_order_num' => '2019081620976878455500663',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-16 10:21:37',
                'created_at' => '2019-08-16 10:21:37',
            ),
            39 => 
            array (
                'id' => 40,
                'user_id' => 16,
                'user_name' => 'ling1',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => '2019081619255147243121824',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-16 21:25:25',
                'created_at' => '2019-08-16 21:25:25',
            ),
            40 => 
            array (
                'id' => 41,
                'user_id' => 36,
                'user_name' => 'alan888',
                'is_tester' => 1,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '50000.000',
                'company_order_num' => '2019081820834620765791769',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-18 01:14:43',
                'created_at' => '2019-08-18 01:14:43',
            ),
            41 => 
            array (
                'id' => 42,
                'user_id' => 66,
                'user_name' => 'jaxton',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '50000.000',
                'company_order_num' => '2019081829663069302694876',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-18 01:29:26',
                'created_at' => '2019-08-18 01:29:26',
            ),
            42 => 
            array (
                'id' => 43,
                'user_id' => 66,
                'user_name' => 'jaxton',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '2000.000',
                'company_order_num' => '2019081884117908282388921',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-18 03:00:11',
                'created_at' => '2019-08-18 03:00:11',
            ),
            43 => 
            array (
                'id' => 44,
                'user_id' => 66,
                'user_name' => 'jaxton',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '2500.000',
                'company_order_num' => '2019081886991242999376321',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-18 03:04:59',
                'created_at' => '2019-08-18 03:04:59',
            ),
            44 => 
            array (
                'id' => 45,
                'user_id' => 66,
                'user_name' => 'jaxton',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '500.000',
                'company_order_num' => '2019081888384200259432873',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-18 03:07:18',
                'created_at' => '2019-08-18 03:07:18',
            ),
            45 => 
            array (
                'id' => 46,
                'user_id' => 66,
                'user_name' => 'jaxton',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '5000.000',
                'company_order_num' => '2019081888873724923747073',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-18 03:08:07',
                'created_at' => '2019-08-18 03:08:07',
            ),
            46 => 
            array (
                'id' => 47,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => NULL,
                'channel' => 'transfer',
                'payment_id' => NULL,
                'amount' => '100.000',
                'company_order_num' => 'R201908282150453528',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 0,
                'client_ip' => '103.42.94.10',
                'source' => 'web',
                'updated_at' => '2019-08-28 21:50:45',
                'created_at' => '2019-08-28 21:50:45',
            ),
            47 => 
            array (
                'id' => 48,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => NULL,
                'channel' => 'transfer',
                'payment_id' => NULL,
                'amount' => '500.000',
                'company_order_num' => 'R201908282156571663',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 0,
                'client_ip' => '103.104.16.186',
                'source' => 'web',
                'updated_at' => '2019-08-28 21:56:57',
                'created_at' => '2019-08-28 21:56:57',
            ),
            48 => 
            array (
                'id' => 49,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => NULL,
                'channel' => 'transfer',
                'payment_id' => NULL,
                'amount' => '10.000',
                'company_order_num' => 'R201908282202349816',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 0,
                'client_ip' => '103.42.94.10',
                'source' => 'web',
                'updated_at' => '2019-08-28 22:02:34',
                'created_at' => '2019-08-28 22:02:34',
            ),
            49 => 
            array (
                'id' => 50,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => NULL,
                'channel' => 'zfb',
                'payment_id' => NULL,
                'amount' => '0.000',
                'company_order_num' => 'R201908282215367582',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 0,
                'client_ip' => '103.42.94.10',
                'source' => 'web',
                'updated_at' => '2019-08-28 22:15:36',
                'created_at' => '2019-08-28 22:15:36',
            ),
            50 => 
            array (
                'id' => 51,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => NULL,
                'channel' => 'zfb',
                'payment_id' => NULL,
                'amount' => '2.000',
                'company_order_num' => 'R201908282215538113',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 0,
                'client_ip' => '103.42.94.10',
                'source' => 'web',
                'updated_at' => '2019-08-28 22:15:53',
                'created_at' => '2019-08-28 22:15:53',
            ),
            51 => 
            array (
                'id' => 52,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => NULL,
                'channel' => 'transfer',
                'payment_id' => NULL,
                'amount' => '0.000',
                'company_order_num' => 'R201908291529245181',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 0,
                'client_ip' => '103.42.94.10',
                'source' => 'web',
                'updated_at' => '2019-08-29 15:29:24',
                'created_at' => '2019-08-29 15:29:24',
            ),
            52 => 
            array (
                'id' => 53,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => NULL,
                'channel' => 'transfer',
                'payment_id' => NULL,
                'amount' => '10.000',
                'company_order_num' => 'R201908291529318689',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 0,
                'client_ip' => '103.42.94.10',
                'source' => 'web',
                'updated_at' => '2019-08-29 15:29:31',
                'created_at' => '2019-08-29 15:29:31',
            ),
            53 => 
            array (
                'id' => 54,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => NULL,
                'channel' => 'transfer',
                'payment_id' => NULL,
                'amount' => '10.000',
                'company_order_num' => 'R201908291536028476',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 0,
                'client_ip' => '103.42.94.10',
                'source' => 'web',
                'updated_at' => '2019-08-29 15:36:02',
                'created_at' => '2019-08-29 15:36:02',
            ),
            54 => 
            array (
                'id' => 55,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'is_tester' => 0,
                'top_agent' => NULL,
                'channel' => 'transfer',
                'payment_id' => NULL,
                'amount' => '0.000',
                'company_order_num' => 'R201908291717284297',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 0,
                'client_ip' => '103.104.16.186',
                'source' => 'web',
                'updated_at' => '2019-08-29 17:17:28',
                'created_at' => '2019-08-29 17:17:28',
            ),
            55 => 
            array (
                'id' => 56,
                'user_id' => 81,
                'user_name' => 'max7777',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '50000.000',
                'company_order_num' => 'XWP8e88274cf991',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-30 16:37:40',
                'created_at' => '2019-08-30 16:37:40',
            ),
            56 => 
            array (
                'id' => 57,
                'user_id' => 82,
                'user_name' => 'max77777',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '50000.000',
                'company_order_num' => 'XWP8e8828c97290',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-30 16:41:49',
                'created_at' => '2019-08-30 16:41:49',
            ),
            57 => 
            array (
                'id' => 58,
                'user_id' => 83,
                'user_name' => 'max886',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '5000.000',
                'company_order_num' => 'XWP8e8837a8b22e',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-30 17:23:24',
                'created_at' => '2019-08-30 17:23:24',
            ),
            58 => 
            array (
                'id' => 59,
                'user_id' => 84,
                'user_name' => 'max789',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '1234.000',
                'company_order_num' => 'XWP8e8838ac3731',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-30 17:26:15',
                'created_at' => '2019-08-30 17:26:15',
            ),
            59 => 
            array (
                'id' => 60,
                'user_id' => 96,
                'user_name' => 'bayern',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => 'XWP8e89ab2c2981',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-31 10:42:14',
                'created_at' => '2019-08-31 10:42:14',
            ),
            60 => 
            array (
                'id' => 61,
                'user_id' => 97,
                'user_name' => 'zxc',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => 'XWP8e89bb0fb02c',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-31 11:26:40',
                'created_at' => '2019-08-31 11:26:40',
            ),
            61 => 
            array (
                'id' => 62,
                'user_id' => 97,
                'user_name' => 'zxc',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '18000.000',
                'company_order_num' => 'XWP8e8a40fc0c6b',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-31 17:41:08',
                'created_at' => '2019-08-31 17:41:08',
            ),
            62 => 
            array (
                'id' => 63,
                'user_id' => 97,
                'user_name' => 'zxc',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '18000.000',
                'company_order_num' => 'XWP8e8a4532c508',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-31 17:52:55',
                'created_at' => '2019-08-31 17:52:55',
            ),
            63 => 
            array (
                'id' => 64,
                'user_id' => 97,
                'user_name' => 'zxc',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => 'XWP8e8a4ab109c7',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-31 18:08:17',
                'created_at' => '2019-08-31 18:08:17',
            ),
            64 => 
            array (
                'id' => 65,
                'user_id' => 97,
                'user_name' => 'zxc',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => 'XWP8e8a4ac62a7d',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-31 18:08:31',
                'created_at' => '2019-08-31 18:08:31',
            ),
            65 => 
            array (
                'id' => 66,
                'user_id' => 97,
                'user_name' => 'zxc',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => 'XWP8e8a4ad04ddd',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-31 18:08:37',
                'created_at' => '2019-08-31 18:08:37',
            ),
            66 => 
            array (
                'id' => 67,
                'user_id' => 97,
                'user_name' => 'zxc',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => 'XWP8e8a4ad951aa',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-31 18:08:43',
                'created_at' => '2019-08-31 18:08:43',
            ),
            67 => 
            array (
                'id' => 68,
                'user_id' => 97,
                'user_name' => 'zxc',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => 'XWP8e8a4ae63785',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-31 18:08:52',
                'created_at' => '2019-08-31 18:08:52',
            ),
            68 => 
            array (
                'id' => 69,
                'user_id' => 97,
                'user_name' => 'zxc',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => 'XWP8e8a4aee801f',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-31 18:08:57',
                'created_at' => '2019-08-31 18:08:57',
            ),
            69 => 
            array (
                'id' => 70,
                'user_id' => 97,
                'user_name' => 'zxc',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => 'XWP8e8a4afb45c0',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-08-31 18:09:06',
                'created_at' => '2019-08-31 18:09:06',
            ),
            70 => 
            array (
                'id' => 71,
                'user_id' => 97,
                'user_name' => 'zxc',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => 'XWP8e8e003d0811',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-09-02 14:23:25',
                'created_at' => '2019-09-02 14:23:25',
            ),
            71 => 
            array (
                'id' => 72,
                'user_id' => 81,
                'user_name' => 'max7777',
                'is_tester' => 0,
                'top_agent' => 0,
                'channel' => NULL,
                'payment_id' => NULL,
                'amount' => '90000.000',
                'company_order_num' => 'XWP8e901af3c938',
                'third_party_order_num' => NULL,
                'deposit_mode' => 1,
                'real_amount' => NULL,
                'fee' => NULL,
                'audit_flow_id' => NULL,
                'status' => 11,
                'client_ip' => NULL,
                'source' => NULL,
                'updated_at' => '2019-09-03 15:29:46',
                'created_at' => '2019-09-03 15:29:46',
            ),
        ));
        
        
    }
}