<?php
return [
    ['username' => 'pitiless', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/1.jpg', 'lottery_sign' => '重庆时时彩', 'bonus' => '1960.0000'],
    ['username' => 'memorial', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/2.jpg', 'lottery_sign' => '中兴11选5', 'bonus' => '980.0000'],
    ['username' => 'hickey', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/3.jpg', 'lottery_sign' => '新疆时时彩', 'bonus' => '1260.0000'],
    ['username' => 'miracle', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/4.jpg', 'lottery_sign' => '黑龙江时时彩', 'bonus' => '490.0000'],
    ['username' => 'belief', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/5.jpg', 'lottery_sign' => '香港六合彩', 'bonus' => '360.0000'],
    ['username' => 'unique', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/6.jpg', 'lottery_sign' => '中兴PK10', 'bonus' => '3990.0000'],
    ['username' => 'allure Love', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/7.jpg', 'lottery_sign' => '北京PK10', 'bonus' => '596.0000'],
    ['username' => 'nightmare', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/8.jpg', 'lottery_sign' => '上海时时乐', 'bonus' => '2648.0000'],
    ['username' => 'suffocate', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/9.jpg', 'lottery_sign' => '福彩3D', 'bonus' => '3880.0000'],
    ['username' => 'ambiguous', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/10.jpg', 'lottery_sign' => '安徽快3', 'bonus' => '196.0000'],
    ['username' => 'Waitz', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/11.jpg', 'lottery_sign' => '中兴11选5', 'bonus' => '2480.0000'],
    ['username' => 'each other', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/12.jpg', 'lottery_sign' => '广东11选5', 'bonus' => '96000.0000'],
    ['username' => 'poppies', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/13.jpg', 'lottery_sign' => '重庆时时彩', 'bonus' => '6586.0000'],
    ['username' => 'beta', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/14.jpg', 'lottery_sign' => '中兴1分彩', 'bonus' => '7232.0000'],
    ['username' => 'bInsomnia', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/15.jpg', 'lottery_sign' => '新疆时时彩', 'bonus' => '196.0000'],
    ['username' => 'pluto', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/16.jpg', 'lottery_sign' => '重庆时时彩', 'bonus' => '598.0000'],
    ['username' => 'dot', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/17.jpg', 'lottery_sign' => '黑龙江时时彩', 'bonus' => '2680.0000'],
    ['username' => 'silly', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/18.jpg', 'lottery_sign' => '河南快3', 'bonus' => '5880.0000'],
    ['username' => 'liquor', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/19.jpg', 'lottery_sign' => '福彩3D', 'bonus' => '688.0000'],
    ['username' => 'wex159357', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/20.jpg', 'lottery_sign' => '北京PK10', 'bonus' => '782.0000'],
    ['username' => 'Eddie', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/21.jpg', 'lottery_sign' => '上海时时乐', 'bonus' => '1982.0000'],
    ['username' => 'Fernanda', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/22.jpg', 'lottery_sign' => '香港六合彩', 'bonus' => '298.0000'],
    ['username' => 'Hamilton', 'user_icon' => '/uploaded_files/aa_1/user_aa_1/23.jpg', 'lottery_sign' => '中兴11选5', 'bonus' => '980.0000'],
];
